# -*- coding: utf-8 -*-
"""Copy of Bookjngs_100000

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vE1V3qEW9BB-HdVccVT76_YIIJvgXJ3
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("Bookings-100000-Rows.xlsx")

x = df.columns
for i in x:
 print(i)

print(df.head())
print(df.shape)
print(df.info)
print(df.isnull().sum())
print(df.duplicated().sum())

total = len(df)
total

status_counts = df["Booking_Status"].value_counts()
status_pct = round((status_counts/total)*100, 2)

status_counts

status_pct

"""3. Top 10 Pickup Locations"""

top_pickup = df['Pickup_Location'].value_counts().head(10)
print(top_pickup)

"""4. Vehicle Type Performance"""

vehicle = df['Vehicle_Type'].value_counts()
print(vehicle)

"""5. Cancellation Analysis (IMPORTANT)"""

customer_cancel = df[df['Booking_Status'] == 'Canceled by Customer']
driver_cancel = df[df['Booking_Status'] == 'Canceled by Driver']

print("Customer Cancel:", len(customer_cancel))
print("Driver Cancel:", len(driver_cancel))

"""6. Cancellation Rate %"""

total = len(df)
customer_cancel = df[df['Booking_Status'] == 'Canceled by Customer']
driver_cancel = df[df['Booking_Status'] == 'Canceled by Driver']

cancel_total = len(customer_cancel) + len(driver_cancel)

cancel_rate = round((cancel_total / total) * 100, 2)
print("Cancel Rate:", cancel_rate, "%")

""" 7. Incomplete Rides Reason"""

incomplete = df[df['Booking_Status'] == 'Success']

reason = incomplete['Incomplete_Rides_Reason'].value_counts()
reason

"""8. Payment Method Analysis"""

payment = df['Payment_Method'].value_counts()
payment

""" 9. Revenue Analysis (MOST IMPORTANT)"""

total_revenue = df['Booking_Value'].sum()
avg_value = df['Booking_Value'].mean()

print("Total Revenue:", total_revenue)
print("Avg Booking Value:", avg_value)

"""10. Location Wise Revenue"""

loc_revenue = df.groupby('Pickup_Location')['Booking_Value'].sum().sort_values(ascending=False).head(10)
loc_revenue

"""11. Top 5 locations with highest cancellation rate"""

cancel_df = df[df['Booking_Status'].str.contains("Canceled")]

rate = (cancel_df['Pickup_Location'].value_counts() / df['Pickup_Location'].value_counts()) * 100
rate.sort_values(ascending=False).head(5)

"""12. Avg booking value per vehicle type"""

df.groupby('Vehicle_Type')['Booking_Value'].mean().sort_values(ascending=False)

"""13. Hour with highest bookings"""

df['Hour'] = df['Time'].apply(lambda x: x.hour)
df['Hour'].value_counts().sort_values(ascending=False).head(1)

"""14. Hour with highest cancellations"""

cancel = df[df['Booking_Status'].str.contains("Canceled")]
cancel['Hour'].value_counts().sort_values(ascending=False).head(1)

"""15. Vehicle type with highest revenue"""

df.groupby('Vehicle_Type')['Booking_Value'].sum().sort_values(ascending=False)

"""16. Completed vs Cancel revenue loss"""

completed = df[df['Booking_Status'] == 'Completed']['Booking_Value'].sum()
canceled = df[df['Booking_Status'].str.contains("Canceled")]['Booking_Value'].sum()

print("Completed:", completed)
print("Lost Revenue:", canceled)

"""17. Avg TAT (Vehicle & Customer)"""

print("Vehicle TAT:", df['V_TAT'].mean())
print("Customer TAT:", df['C_TAT'].mean())

"""18. Long rides vs short rides revenue"""

df['Ride_Type'] = df['Ride_Distance'].apply(lambda x: "Long" if x > 10 else "Short")

df.groupby('Ride_Type')['Booking_Value'].sum()

"""19. Repeat locations (high demand consistency)"""

repeat = df['Pickup_Location'].value_counts()
repeat[repeat > 1000]

"""20. Correlation (Distance vs Booking Value)"""

df[['Ride_Distance','Booking_Value']].corr()

"""21. High Demand but Low Success Areas"""

total_loc = df['Pickup_Location'].value_counts()
completed_loc = df[df['Booking_Status']=='Completed']['Pickup_Location'].value_counts()

success_rate = (completed_loc / total_loc) * 100
success_rate.sort_values().head(5)

"""22. Peak Hour + Worst Cancellation Combo"""

df['Hour'] = df['Time'].apply(lambda x: x.hour)

cancel = df[df['Booking_Status'].str.contains("Canceled")]
combo = cancel.groupby('Hour').size()

combo.sort_values(ascending=False).head(3)

"""23. Revenue Leakage (serious metric)"""

potential = df['Booking_Value'].sum()
actual = df[df['Booking_Status']=='Completed']['Booking_Value'].sum()

leakage = potential - actual
print("Revenue Leakage:", leakage)

"""24. Vehicle Efficiency Score"""

completed = df[df['Booking_Status']=='Completed']

eff = completed.groupby('Vehicle_Type').agg({
    'Booking_ID':'count',
    'Booking_Value':'sum'
})

eff['Efficiency'] = eff['Booking_Value'] / eff['Booking_ID']
eff.sort_values(by='Efficiency', ascending=False)

"""25. Cancellation Reason Impact"""

reason_impact = df[df['Booking_Status'].str.contains("Canceled")]['Incomplete_Rides_Reason'].value_counts()
reason_impact

"""26. Customer Wait vs Cancel Relation"""

cancel = df[df['Booking_Status'].str.contains("Canceled")]
print(cancel['C_TAT'].mean())

completed = df[df['Booking_Status']=='Completed']
completed['C_TAT'].mean()

"""27. Top Revenue Hours"""

rev_hour = df.groupby('Hour')['Booking_Value'].sum()
print(rev_hour.sort_values(ascending=False).head(5))

"""28. Distance vs Cancellation"""

df['Ride_Type'] = df['Ride_Distance'].apply(lambda x: "Long" if x > 10 else "Short")

cancel = df[df['Booking_Status'].str.contains("Canceled")]
print(cancel['Ride Type'].value_counts())

"""29. Location-wise Avg Ride Value"""

avg_loc = df.groupby('Pickup_Location')['Booking_Value'].mean()
avg_loc.sort_values(ascending=False).head(10)

"""30. Funnel Analysis (MOST IMPORTANT)"""

total = len(df)
completed = len(df[df['Booking_Status']=='Completed'])
canceled = len(df[df['Booking_Status'].str.contains("Canceled")])
incomplete = len(df[df['Booking_Status']=='Incomplete'])

print("Total:", total)
print("Completed:", completed)
print("Canceled:", canceled)
print("Incomplete:", incomplete)

I= df.columns
for i in I:
 print(i)

Total_Bookings = df.[Booking_ID]
Total_Bookings